MAILCHIMP_SUBSCRIBE_LIST_ID = ENV['MAILCHIMP_SUBSCRIBE_LIST']
MAILCHIMP_PURCHASE_LIST_ID = ENV['MAILCHIMP_PURCHASE_LIST']
MAILCHIMP_API_KEY = ENV['MAILCHIMP_API_KEY']
YANDEX_DISK_ACCESS_TOKEN = ENV['YANDEX_DISK_ACCESS_TOKEN']
